packages:
  - "packages/common/*/*"
  - "packages/native-rust/*/*"
  - "packages/native-rust/routes/*/*"
  - "packages/pc-react/*/*"
  - "packages/mobile-react/*/*"
  - "../sdkwork-sdk-commons/sdkwork-sdk-common-typescript"
  - "sdks/*"
  - "sdks/sdkwork-search-app-sdk/sdkwork-search-app-sdk-typescript/generated/server-openapi"
  - "sdks/sdkwork-search-backend-sdk/sdkwork-search-backend-sdk-typescript/generated/server-openapi"
