pub const SEARCH_BACKEND_API_PREFIX: &str = "/backend/v3/api";
pub const SEARCH_BACKEND_API_AUTHORITY: &str = "sdkwork-search-backend-api";
pub const SEARCH_BACKEND_SDK_FAMILY: &str = "sdkwork-search-backend-sdk";
pub const SEARCH_BACKEND_API_AUTH_MODE: &str = "dual-token";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SearchRouteManifest {
    pub kind: &'static str,
    pub package_name: &'static str,
    pub surface: &'static str,
    pub owner: &'static str,
    pub domain: &'static str,
    pub capability: &'static str,
    pub api_authority: &'static str,
    pub sdk_family: &'static str,
    pub prefix: &'static str,
    pub routes: Vec<SearchRoute>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SearchRoute {
    pub method: &'static str,
    pub path: &'static str,
    pub operation_id: &'static str,
    pub tag: &'static str,
    pub auth_mode: &'static str,
    pub handler_module: &'static str,
    pub handler_name: &'static str,
    pub request_schema: Option<&'static str>,
    pub response_schema: &'static str,
    pub ownership_owner: &'static str,
    pub ownership_api_authority: &'static str,
    pub source_route_crate: &'static str,
}

pub fn search_backend_api_manifest() -> SearchRouteManifest {
    SearchRouteManifest {
        kind: "sdkwork.route.manifest",
        package_name: "sdkwork-routes-search-backend-api",
        surface: "backend-api",
        owner: "sdkwork-search",
        domain: "search",
        capability: "search",
        api_authority: SEARCH_BACKEND_API_AUTHORITY,
        sdk_family: SEARCH_BACKEND_SDK_FAMILY,
        prefix: SEARCH_BACKEND_API_PREFIX,
        routes: vec![
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/indexes",
                operation_id: "search.indexes.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_indexes",
                request_schema: None,
                response_schema: "SearchIndexListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/indexes",
                operation_id: "search.indexes.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_index",
                request_schema: Some("SearchIndexCreateRequest"),
                response_schema: "SearchIndexResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "PATCH",
                path: "/backend/v3/api/search/indexes/{indexId}",
                operation_id: "search.indexes.update",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "update_search_index",
                request_schema: Some("SearchIndexUpdateRequest"),
                response_schema: "SearchIndexResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "DELETE",
                path: "/backend/v3/api/search/indexes/{indexId}",
                operation_id: "search.indexes.delete",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "delete_search_index",
                request_schema: None,
                response_schema: "SearchIndexDeleteResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "PUT",
                path: "/backend/v3/api/search/indexes/{indexId}/documents/{documentId}",
                operation_id: "search.documents.upsert",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "upsert_search_document",
                request_schema: Some("SearchDocumentUpsertRequest"),
                response_schema: "SearchDocumentResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/indexes/{indexId}/documents/bulk_upsert",
                operation_id: "search.documents.bulkUpsert",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "bulk_upsert_search_documents",
                request_schema: Some("SearchDocumentBulkUpsertRequest"),
                response_schema: "SearchDocumentBulkUpsertResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "DELETE",
                path: "/backend/v3/api/search/indexes/{indexId}/documents/{documentId}",
                operation_id: "search.documents.delete",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "delete_search_document",
                request_schema: None,
                response_schema: "SearchDocumentDeleteResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/synonyms",
                operation_id: "search.synonyms.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_synonyms",
                request_schema: None,
                response_schema: "SearchSynonymListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/synonyms",
                operation_id: "search.synonyms.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_synonym",
                request_schema: Some("SearchSynonymCreateRequest"),
                response_schema: "SearchSynonymResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "DELETE",
                path: "/backend/v3/api/search/synonyms/{synonymId}",
                operation_id: "search.synonyms.delete",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "delete_search_synonym",
                request_schema: None,
                response_schema: "SearchSynonymDeleteResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/ranking_profiles",
                operation_id: "search.rankingProfiles.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_ranking_profiles",
                request_schema: None,
                response_schema: "SearchRankingProfileListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/ranking_profiles",
                operation_id: "search.rankingProfiles.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_ranking_profile",
                request_schema: Some("SearchRankingProfileCreateRequest"),
                response_schema: "SearchRankingProfileResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "PATCH",
                path: "/backend/v3/api/search/ranking_profiles/{profileId}",
                operation_id: "search.rankingProfiles.update",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "update_search_ranking_profile",
                request_schema: Some("SearchRankingProfileUpdateRequest"),
                response_schema: "SearchRankingProfileResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/recommendation_strategies",
                operation_id: "search.recommendationStrategies.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_recommendation_strategies",
                request_schema: None,
                response_schema: "SearchRecommendationStrategyListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/recommendation_strategies",
                operation_id: "search.recommendationStrategies.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_recommendation_strategy",
                request_schema: Some("SearchRecommendationStrategyCreateRequest"),
                response_schema: "SearchRecommendationStrategyResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "PATCH",
                path: "/backend/v3/api/search/recommendation_strategies/{strategyId}",
                operation_id: "search.recommendationStrategies.update",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "update_search_recommendation_strategy",
                request_schema: Some("SearchRecommendationStrategyUpdateRequest"),
                response_schema: "SearchRecommendationStrategyResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/promotions",
                operation_id: "search.promotions.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_promotions",
                request_schema: None,
                response_schema: "SearchPromotionListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/promotions",
                operation_id: "search.promotions.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_promotion",
                request_schema: Some("SearchPromotionCreateRequest"),
                response_schema: "SearchPromotionAdminResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "PATCH",
                path: "/backend/v3/api/search/promotions/{promotionId}",
                operation_id: "search.promotions.update",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "update_search_promotion",
                request_schema: Some("SearchPromotionUpdateRequest"),
                response_schema: "SearchPromotionAdminResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "DELETE",
                path: "/backend/v3/api/search/promotions/{promotionId}",
                operation_id: "search.promotions.delete",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "delete_search_promotion",
                request_schema: None,
                response_schema: "SearchPromotionDeleteResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/embedding_jobs",
                operation_id: "search.embeddingJobs.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_embedding_jobs",
                request_schema: None,
                response_schema: "SearchEmbeddingJobListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/embedding_jobs",
                operation_id: "search.embeddingJobs.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_embedding_job",
                request_schema: Some("SearchEmbeddingJobCreateRequest"),
                response_schema: "SearchEmbeddingJobResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/embedding_jobs/{jobId}/retry",
                operation_id: "search.embeddingJobs.retry",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "retry_search_embedding_job",
                request_schema: None,
                response_schema: "SearchEmbeddingJobResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/ab_experiments",
                operation_id: "search.abExperiments.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_ab_experiments",
                request_schema: None,
                response_schema: "SearchAbExperimentListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/ab_experiments",
                operation_id: "search.abExperiments.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_ab_experiment",
                request_schema: Some("SearchAbExperimentCreateRequest"),
                response_schema: "SearchAbExperimentResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "PATCH",
                path: "/backend/v3/api/search/ab_experiments/{experimentId}",
                operation_id: "search.abExperiments.update",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "update_search_ab_experiment",
                request_schema: Some("SearchAbExperimentUpdateRequest"),
                response_schema: "SearchAbExperimentResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/ab_experiments/{experimentId}/assignments",
                operation_id: "search.abExperiments.assign",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "assign_search_ab_experiment",
                request_schema: Some("SearchAbAssignmentRequest"),
                response_schema: "SearchAbAssignmentResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/jobs/rebuild",
                operation_id: "search.jobs.rebuild.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_rebuild_job",
                request_schema: Some("SearchRebuildJobRequest"),
                response_schema: "SearchIndexJobResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/analytics/overview",
                operation_id: "search.analytics.overview.retrieve",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "retrieve_search_analytics_overview",
                request_schema: None,
                response_schema: "SearchAnalyticsOverview",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "GET",
                path: "/backend/v3/api/search/providers",
                operation_id: "search.providers.list",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "list_search_providers",
                request_schema: None,
                response_schema: "SearchProviderListResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/providers",
                operation_id: "search.providers.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_provider",
                request_schema: Some("SearchProviderCreateRequest"),
                response_schema: "SearchProviderResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "PATCH",
                path: "/backend/v3/api/search/providers/{providerId}",
                operation_id: "search.providers.update",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "update_search_provider",
                request_schema: Some("SearchProviderUpdateRequest"),
                response_schema: "SearchProviderResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
            SearchRoute {
                method: "POST",
                path: "/backend/v3/api/search/providers/{providerId}/health_checks",
                operation_id: "search.providers.healthChecks.create",
                tag: "search",
                auth_mode: SEARCH_BACKEND_API_AUTH_MODE,
                handler_module: "crate::handlers",
                handler_name: "create_search_provider_health_check",
                request_schema: None,
                response_schema: "SearchProviderHealthCheckResponse",
                ownership_owner: "sdkwork-search",
                ownership_api_authority: SEARCH_BACKEND_API_AUTHORITY,
                source_route_crate: "sdkwork-routes-search-backend-api",
            },
        ],
    }
}
