//! Route manifest for search backend-api (`WEB_BACKEND_SPEC.md`).

use crate::paths;
use sdkwork_web_contract::{HttpMethod, HttpRoute};

pub const ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::indexes::COLLECTION,
        "search",
        "search.indexes.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::indexes::COLLECTION,
        "search",
        "search.indexes.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::indexes::BY_KEY,
        "search",
        "search.indexes.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        paths::indexes::BY_KEY,
        "search",
        "search.indexes.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::indexes::REBUILD,
        "search",
        "search.indexes.rebuild",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::providers::COLLECTION,
        "search",
        "search.providers.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::providers::HEALTH,
        "search",
        "search.providers.health",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::documents::COLLECTION,
        "search",
        "search.documents.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        paths::documents::BY_ID,
        "search",
        "search.documents.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::documents::INDEX,
        "search",
        "search.documents.index",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::documents::BATCH,
        "search",
        "search.documents.batch",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::recommendations::STRATEGIES,
        "search",
        "search.recommendations.strategies.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::promotions::COLLECTION,
        "search",
        "search.promotions.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        paths::promotions::COLLECTION,
        "search",
        "search.promotions.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        paths::audit::PATH,
        "search",
        "search.audit.list",
    ),
];
