//! Generated gateway bootstrap for sdkwork-search.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().
//!
//! `assemble_application_router` 接收由调用方构造好的 route state，
//! state 持有 4 个 service 的 Arc 引用，gateway-assembly 只负责合并两个 surface 路由器。

use axum::Router;
use sdkwork_routes_search_app_api::SearchAppState;
use sdkwork_routes_search_backend_api::SearchBackendState;

pub struct ApplicationAssembly {
    pub router: Router,
}

/// 合并 app-api 与 backend-api 两个 surface 路由器。
///
/// 调用方需先构造好 `SearchAppState` 与 `SearchBackendState`（包含 4 个 service 的 Arc），
/// 再传入本函数。gateway-assembly 本身不负责 service 构造。
pub fn assemble_application_router(
    app_state: SearchAppState,
    backend_state: SearchBackendState,
) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_search_app_api::gateway_mount(app_state));
    router = router.merge(sdkwork_routes_search_backend_api::gateway_mount(
        backend_state,
    ));
    ApplicationAssembly { router }
}
